[package]
name = "aurora"
version = "0.1.0"
edition = "2021"

[dependencies]
glam = "0.29.2"
indicatif = { version = "0.17.9", features = ["rayon"] }
itertools = "0.13.0"
pixels = "0.15.0"
rand =  { version = "0.8.5", features = ["small_rng"] }
rayon = "1.10.0"
winit = "0.30.9"
